### ISSUE TITLE
Provide the lemma DB raw data ?

### ISSUE THREAD

**Issue by PonteIneptique** [CIRCSE/LEMLAT3#16]
Hi there :)
I have been seeing the project multiple time but one of the things that troubles me is the unability to find the list of lemma, say in a raw format like CSV/TSV. I think it would be pretty helpful to have access to this kind of list, as user of the application.

Cheers !

**Comment by gersh0m** [comment]
Hi,
If you mean the list of all lemmas that Lemlat can generate they are all stored in the table 'lemmario' that you can find in the lemlat_db dump file: they are not 'raw' format actually, but it should be quite easy to extract them in the desired format (dump file it's just plain-standard sql).
If you mean the list of the lemmas 'linked' to a specific list of forms you can get them directly in raw format giving the correct parameters to the provided application (see usage on the home page).

**Comment by gfranzini** [comment]
@PonteIneptique `csv` and `tsv` versions of the lemmario are now available here: https://github.com/CIRCSE/LEMLAT3/tree/master/lemlat_workspace/LemLat_Data

**Comment by PonteIneptique** [comment]
As we say in French : un prêté pour un rendu !
Or simply : thanks !

**Comment by gfranzini** [comment]
De rien! :)
