### ISSUE TITLE
Running on Windows 10 64-bi

### ISSUE THREAD

**Issue by pisteuomen** [CIRCSE/LEMLAT3#8]
Hello,
I have tried running LemLat3 on Windows 10 64-bit and cannot get it to work. I have even tried running it in compatibility mode with Windows 8 but it simply opens and about a second later closes. Is there a way to run it on the Windows 10 64-bit platform?

**Comment by gersh0m** [comment]
Hi,

both version (embedded and client) where tested on windows 10 64 bits without any problem.
Can you please give further details of the step you have done, in order to reproduce the issue?
Which version did you use? how did you set it up? etc...

**Comment by gersh0m** [comment]
...as in previous answer
